# Taps
tap "homebrew/bundle"
tap "jandedobbeleer/oh-my-posh"

# Shell & Terminal
brew "zsh"
brew "oh-my-posh"
brew "fish"

# Development
brew "git"
brew "gh"
brew "neovim"
brew "node"
brew "go"

# Utilities
brew "jq"
brew "scrcpy"

# Casks
cask "claude-code@latest"
cask "codexbar"
cask "font-meslo-lg-nerd-font"
cask "gcloud-cli"
cask "ghostty"
cask "hot"
cask "kap"
cask "minisim"
cask "notion-calendar"
