# Taps
tap "homebrew/bundle"
tap "jandedobbeleer/oh-my-posh"

# Shell & Terminal
brew "zsh"
brew "oh-my-posh"
brew "fish"

# Development
brew "git"
brew "gh"
brew "neovim"
brew "node"
brew "go"
brew "fvm"

# Utilities
brew "jq"

# Casks
cask "font-meslo-lg-nerd-font"
